### ISSUE TITLE
ListConfig errors when is [:-1] applied to empty list

### ISSUE THREAD

**Issue by YodaEmbedding** [omry/omegaconf#1086]
**Describe the bug**
ListConfig errors when is [:-1] applied to empty list.

**To Reproduce**

```python
>>> from omegaconf import OmegaConf
>>> conf = OmegaConf.create({"a": None, "b": "keyname", "${b}": "${b} wow dynamic", "xs": []})
>>> conf.xs[:-1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.11/site-packages/omegaconf/listconfig.py", line 218, in __getitem__
    self._format_and_raise(key=index, value=None, cause=e)
  File "/usr/lib/python3.11/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/usr/lib/python3.11/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/usr/lib/python3.11/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/omegaconf/listconfig.py", line 203, in __getitem__
    for slice_idx in itertools.islice(
                     ^^^^^^^^^^^^^^^^^
ValueError: Stop argument for islice() must be None or an integer: 0 <= x <= sys.maxsize.
    full_key: xs[None:-1]
    object_type=list
```

**Expected behavior**
```python
>>> xs = []
>>> xs[:-1]
[]
```

**Additional context**
- [ ] OmegaConf version: 2.3.0
- [ ] Python version: 3.11
- [ ] Operating system: Arch Linux
- [ ] Please provide a minimal repro

**Comment by Jasha10** [comment]
Thanks @YodaEmbedding.

For reference, here is comparison with the current behavior for python's built-in `list` type:
```python
>>> [][:-1]
[]
```
