### ISSUE TITLE
Support erroring when field that does not exist is accessed.

### ISSUE THREAD

**Issue by omry** [omry/omegaconf#20]
Freeze is nice, but does not work for unintended reads.
It's possible that the real solution here would be to relay on node level validation.

```
>>> a =  OmegaConf.empty()
>>> a.foo
>>> a.freeze(True)
>>> a
{}
>>> a.foo
>>>
>>> a.foo = a
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/home/omry/dev/omegaconf.git/omegaconf/dictconfig.py", line 47, in __setattr__
    self.__setitem__(key, value)
  File "/private/home/omry/dev/omegaconf.git/omegaconf/dictconfig.py", line 26, in __setitem__
    raise FrozenConfigError(self.get_full_key(key))
omegaconf.errors.FrozenConfigError: foo
```

**Comment by omry** [comment]
initial implementation at 845b1a0c82e515459b49015171837dab30d1007d
