### ISSUE TITLE
AssertionError constructued Structured Config with nested MISSING fields

### ISSUE THREAD

**Issue by jieru-hu** [omry/omegaconf#206]
my script ```my_test.py```

```python3
from dataclasses import MISSING, dataclass
from typing import Optional
from omegaconf import OmegaConf

@dataclass
class AConf:
    count: Optional[int] = MISSING

@dataclass
class SimpleConf:
    aconf: AConf = MISSING

def my_app() -> None:
    conf1 = OmegaConf.structured(SimpleConf)

if __name__ == "__main__":
    my_app()

```

run ```python my_test.py```

stack trace:
```bash
(hydra37) jieru-mbp:hydra jieru$ python /Users/jieru/workspace/hydra-fork/hydra/plugins/hydra_ray_launcher/my_test.py
Traceback (most recent call last):
  File "/Users/jieru/workspace/hydra-fork/hydra/plugins/hydra_ray_launcher/my_test.py", line 25, in <module>
    my_app()
  File "/Users/jieru/workspace/hydra-fork/hydra/plugins/hydra_ray_launcher/my_test.py", line 20, in my_app
    conf1 = OmegaConf.structured(SimpleConf)
  File "/Users/jieru/workspace/omegaconf/omegaconf/omegaconf.py", line 133, in structured
    return OmegaConf.create(obj, parent)
  File "/Users/jieru/workspace/omegaconf/omegaconf/omegaconf.py", line 160, in create
    return OmegaConf._create_impl(obj=obj, parent=parent)
  File "/Users/jieru/workspace/omegaconf/omegaconf/omegaconf.py", line 194, in _create_impl
    return DictConfig(content=obj, parent=parent, ref_type=ref_type)
  File "/Users/jieru/workspace/omegaconf/omegaconf/dictconfig.py", line 69, in __init__
    self._set_value(content)
  File "/Users/jieru/workspace/omegaconf/omegaconf/dictconfig.py", line 505, in _set_value
    data = get_structured_config_data(value)
  File "/Users/jieru/workspace/omegaconf/omegaconf/_utils.py", line 225, in get_structured_config_data
    return get_dataclass_data(obj)
  File "/Users/jieru/workspace/omegaconf/omegaconf/_utils.py", line 169, in get_dataclass_data
    ref_type=type_, is_optional=is_optional, key=name, value=value, parent=None,
  File "/Users/jieru/workspace/omegaconf/omegaconf/omegaconf.py", line 681, in _maybe_wrap
    parent=parent,
  File "/Users/jieru/workspace/omegaconf/omegaconf/dictconfig.py", line 69, in __init__
    self._set_value(content)
  File "/Users/jieru/workspace/omegaconf/omegaconf/dictconfig.py", line 490, in _set_value
    self._validate_set(key=None, value=value)
  File "/Users/jieru/workspace/omegaconf/omegaconf/dictconfig.py", line 127, in _validate_set
    self._validate_set_merge_impl(key, value, is_assign=True)
  File "/Users/jieru/workspace/omegaconf/omegaconf/dictconfig.py", line 186, in _validate_set_merge_impl
    value_type = OmegaConf.get_type(value)
  File "/Users/jieru/workspace/omegaconf/omegaconf/omegaconf.py", line 491, in get_type
    assert False, f"Unexpected type : {c}"
AssertionError: Unexpected type : <dataclasses._MISSING_TYPE object at 0x7f8f1004ef90>
```

If I fill both the MISSING values, this issue goes away.

```python
from dataclasses import MISSING, dataclass, field
from typing import Optional
from omegaconf import OmegaConf

@dataclass
class AConf:
    count: Optional[int] = 1

@dataclass
class SimpleConf:
    aconf: AConf = field(default_factory=AConf)

def my_app() -> None:
    conf1 = OmegaConf.structured(SimpleConf)

if __name__ == "__main__":
    my_app()

```

**Comment by omry** [comment]
Okay, that surprised me.
you imported:
```
from dataclasses import MISSING
```

and not:
```
from omegaconf import MISSING
```

I should support dataclass.MISSING too.
