### ISSUE TITLE
[Bug] Crash when using postponed evaluation of annotations

### ISSUE THREAD

**Issue by odelalleau** [omry/omegaconf#303]
# 🐛 Bug

Structured configs seem not to work with the upcoming postponed evaluation of annotations (https://www.python.org/dev/peps/pep-0563/) which will be the default in Python 3.10.

Obviously not really a problem yet but flagging it now as a FYI.

## To reproduce

** Minimal Code/Config snippet to reproduce **

```
from __future__ import annotations

from dataclasses import dataclass
from omegaconf import OmegaConf

@dataclass
class Config:
    a: int = 0

cfg = OmegaConf.structured(Config)
```

** Stack trace/error message **
```
Traceback (most recent call last):
  File "test2.py", line 10, in <module>
    cfg = OmegaConf.structured(Config)
  File "/private/home/odelalleau/.conda/envs/py37-hydra/lib/python3.7/site-packages/omegaconf/omegaconf.py", line 134, in structured
    return OmegaConf.create(obj, parent)
  File "/private/home/odelalleau/.conda/envs/py37-hydra/lib/python3.7/site-packages/omegaconf/omegaconf.py", line 171, in create
    return OmegaConf._create_impl(obj=obj, parent=parent)
  File "/private/home/odelalleau/.conda/envs/py37-hydra/lib/python3.7/site-packages/omegaconf/omegaconf.py", line 220, in _create_impl
    element_type=element_type,
  File "/private/home/odelalleau/.conda/envs/py37-hydra/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 74, in __init__
    self._set_value(content)
  File "/private/home/odelalleau/.conda/envs/py37-hydra/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 546, in _set_value
    data = get_structured_config_data(value)
  File "/private/home/odelalleau/.conda/envs/py37-hydra/lib/python3.7/site-packages/omegaconf/_utils.py", line 258, in get_structured_config_data
    return get_dataclass_data(obj)
  File "/private/home/odelalleau/.conda/envs/py37-hydra/lib/python3.7/site-packages/omegaconf/_utils.py", line 202, in get_dataclass_data
    ref_type=type_, is_optional=is_optional, key=name, value=value, parent=None,
  File "/private/home/odelalleau/.conda/envs/py37-hydra/lib/python3.7/site-packages/omegaconf/omegaconf.py", line 681, in _maybe_wrap
    key=key,
  File "/private/home/odelalleau/.conda/envs/py37-hydra/lib/python3.7/site-packages/omegaconf/omegaconf.py", line 641, in _node_wrap
    elif issubclass(type_, Enum):
TypeError: issubclass() arg 1 must be a class
```

**Comment by omry** [comment]
What is this supposed to do?

**Comment by omry** [comment]
Okay, I saw the answer in the pep. Thanks for the heads up.

**Comment by seminumber** [comment]
I came here to report the same bug. This is truly a bug that I encountered (using other third party tools hydra-core) and took me a whole day to figure out what is being wrong, largely because the TypeError output message is very hard to decipher. Please also consider making early assertions so that the type error reads more sensible (like type annotation for field xx is missing..)

**Comment by omry** [comment]
Are you using Python 3.10?
This issue is specific to it. Since it's not officially or even easily available yet I am surprised you ran into it.

**Comment by omry** [comment]
If you are not using Python 3.10 (as I suspect is the case), please file a different issue with a minimal repro.

**Comment by thomkeh** [comment]
If `from __future__ import annotations` is used (as in the code snippet at the top), then this also happens in Python 3.7+. I just reproduced it with `Python 3.7.7`.

The solution should be simple: instead of accessing `cls.__annotations__` directly, use `typing.get_type_hints(cls)`.

**Comment by omry** [comment]
At this point this is low priority, but feel free to send a pull request.

**Comment by gibiansky** [comment]
I just hit this issue, please merge this PR ASAP! In my experience almost all code that uses types heavily uses `from __future__ import annotations`, so this is fairly serious.

**Comment by omry** [comment]
@gibiansky, mind jumping into the [chat](https://hydra-framework.zulipchat.com/login/) to tell me more about your use case?
This issue has not been a priority and the is currently no plan to fix it in 2.0 (and 2.1 is still months away).

**Comment by gibiansky** [comment]
A relatively clean workaround is to put your config types / dataclasses in a separate file in which you don't use `from __future__ import annotations` , then import those, since the future import is per-file.

**Comment by cbows** [comment]
I am hitting the same issue with omegaconf 2.0.6 on Python 3.7.9. Will this go into a patch release on 2.0.x or will it be released as part of 2.1?

**Comment by omry** [comment]
It is planned to be released with 2.1.
If you don't mind trying a dev release, you can use 2.1.0dev* (be sure to report any issues).

Note that there are some known breaking changes, you can look at the [news](https://github.com/omry/omegaconf/tree/master/news) directory for *.api_change.
