### ISSUE TITLE
Support for Optional[Dict] = None on Python 3.7, 3.8

### ISSUE THREAD

**Issue by blisc** [omry/omegaconf#325]
The following piece of code works on python 3.6, but not python 3.7, nor python 3.8 on Ubuntu.
```python
from omegaconf import OmegaConf
from dataclasses import dataclass
from typing import Dict, Optional
import sys


@dataclass
class TestConfig:
    myDict: Optional[Dict] = None


print(sys.version)
schema = OmegaConf.structured(TestConfig)
```

python3.6 output
```
3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0]
```
python3.7 output
```
3.7.5 (default, Nov  7 2019, 10:50:52) 
[GCC 8.3.0]
Traceback (most recent call last):
  File "omconf_min.py", line 13, in <module>
    schema = OmegaConf.structured(TestConfig)
  File "/home/jasoli/py37_venv_test/lib/python3.7/site-packages/omegaconf/omegaconf.py", line 136, in structured
    return OmegaConf.create(obj, parent)
  File "/home/jasoli/py37_venv_test/lib/python3.7/site-packages/omegaconf/omegaconf.py", line 173, in create
    return OmegaConf._create_impl(obj=obj, parent=parent)
  File "/home/jasoli/py37_venv_test/lib/python3.7/site-packages/omegaconf/omegaconf.py", line 241, in _create_impl
    format_and_raise(node=None, key=None, value=None, msg=str(e), cause=e)
  File "/home/jasoli/py37_venv_test/lib/python3.7/site-packages/omegaconf/_utils.py", line 628, in format_and_raise
    _raise(ex, cause)
  File "/home/jasoli/py37_venv_test/lib/python3.7/site-packages/omegaconf/_utils.py", line 553, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ValidationError: Unsupported key type ~KT, Unsupported value type : ~VT
        full_key: 
        reference_type=None
        object_type=None
```
python3.8 output
```
3.8.0 (default, Oct 28 2019, 16:14:01) 
[GCC 8.3.0]
Traceback (most recent call last):
  File "omconf_min.py", line 13, in <module>
    schema = OmegaConf.structured(TestConfig)
  File "/home/jasoli/py38_venv_test/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 133, in structured
    return OmegaConf.create(obj, parent)
  File "/home/jasoli/py38_venv_test/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 170, in create
    return OmegaConf._create_impl(obj=obj, parent=parent)
  File "/home/jasoli/py38_venv_test/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 238, in _create_impl
    format_and_raise(node=None, key=None, value=None, msg=str(e), cause=e)
  File "/home/jasoli/py38_venv_test/lib/python3.8/site-packages/omegaconf/_utils.py", line 590, in format_and_raise
    raise_(ex, cause)
  File "/home/jasoli/py38_venv_test/lib/python3.8/site-packages/omegaconf/_utils.py", line 515, in raise_
    raise ex
omegaconf.errors.ValidationError: Unsupported value type : ~VT
        full_key: 
        reference_type=None
        object_type=None
```

Can I ask why this is happening? And if a fix for python3.7 and 3.8 will be coming?

**Comment by blisc** [comment]
Actually I found a workaround, it seems like `myDict: Optional[Dict[Any, Any]] = None` seems to work just fine, but `myDict: Optional[Dict] = None` does not.

**Comment by omry** [comment]
Thanks for reporting.
You can use Dict[Any,Any], or be more specific.
the key can be a string or an enum, and the value can be a string, int, float, bool, enum or another dataclass.

We can improve OmegaConf to accept it as Dict[Any, Any] (and List as List[Any]).

**Comment by omry** [comment]
Not making the cutoff for 2.0.1, this will likely be added in the next major version.
