### ISSUE TITLE
Variable Interpolation Bug

### ISSUE THREAD

**Issue by kchua** [omry/omegaconf#35]
OmegaConf runs into issues when the config object is constructed by incrementally adding new OmegaConf objects.

To reproduce:
```
conf = OmegaConf.create()
conf.a = 1
conf.b = OmegaConf.create()
conf.b.c = "${a}"
```

With `conf` above, trying to access `conf.b.c` gets me the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/home/kchua13/.conda/envs/hierarchy/lib/python3.6/site-packages/omegaconf/dictconfig.py", line 72, in __getattr__
    return self.get(key=key, default_value=None)
  File "/private/home/kchua13/.conda/envs/hierarchy/lib/python3.6/site-packages/omegaconf/dictconfig.py", line 83, in get
    return self._resolve_with_default(key=key, value=self.get_node(key), default_value=default_value)
  File "/private/home/kchua13/.conda/envs/hierarchy/lib/python3.6/site-packages/omegaconf/config.py", line 131, in _resolve_with_default
    return self._resolve_single(value) if isinstance(value, str) else value
  File "/private/home/kchua13/.conda/envs/hierarchy/lib/python3.6/site-packages/omegaconf/config.py", line 426, in _resolve_single
    return Config._resolve_value(root, match.group(1), match.group(2))
  File "/private/home/kchua13/.conda/envs/hierarchy/lib/python3.6/site-packages/omegaconf/config.py", line 407, in _resolve_value
    raise KeyError("{} interpolation key '{}' not found".format(inter_type, inter_key))
KeyError: "str interpolation key 'a' not found"
```

**Comment by omry** [comment]
BTW, The recommended API is:
```
conf = OmegaConf.create()
conf.a = 1
conf.b = {}
conf.b.c = "${a}"
```
