### ISSUE TITLE
Default Value not working

### ISSUE THREAD

**Issue by terrykong** [omry/omegaconf#405]
**Describe the bug**

Not sure if this is a hydra issue or an omegaconf issue, but I am unable to specify a default value for a missing key in my DictConfig. Reference: https://omegaconf.readthedocs.io/en/2.0_branch/usage.html#default-values

**To Reproduce**
Please provide a minimal repro.
This can include a small Python file, and potentially a few small config files.
If you have more than one file you can attach a zip file with everything to the issue.

`/tmp/foo/config.yaml`:
```yaml
a: d
b:
  bake: 4
```

`/tmp/foo/main.py`:
```python
import hydra
from omegaconf import OmegaConf

@hydra.main(config_path='/tmp/foo', config_name='config')
def main(cfg):
    print(OmegaConf.to_yaml(cfg))
    print(cfg.b)
    print(cfg.b.get('a', 'HAHAHA'))
    print(cfg.b.a or "NOPE")

main()
```

And oddly the `cfg.b.a` line errors:
```
HYDRA_FULL_ERROR=1 python main.py
/Users/terry/anaconda3/lib/python3.7/site-packages/omegaconf/omegaconf.py:579: UserWarning: update() merge flag is is not specified, defaulting to False.
For more details, see https://github.com/omry/omegaconf/issues/367
  stacklevel=1,
a: d
b:
  bake: 4
exists: true

{'bake': 4}
HAHAHA
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    main()
  File "/Users/terry/anaconda3/lib/python3.7/site-packages/hydra/main.py", line 37, in decorated_main
    strict=strict,
  File "/Users/terry/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 356, in _run_hydra
    lambda: hydra.run(
  File "/Users/terry/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 210, in run_and_report
    raise ex
  File "/Users/terry/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 207, in run_and_report
    return func()
  File "/Users/terry/anaconda3/lib/python3.7/site-packages/hydra/_internal/utils.py", line 359, in <lambda>
    overrides=args.overrides,
  File "/Users/terry/anaconda3/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 112, in run
    configure_logging=with_log_configuration,
  File "/Users/terry/anaconda3/lib/python3.7/site-packages/hydra/core/utils.py", line 125, in run_job
    ret.return_value = task_function(task_cfg)
  File "main.py", line 9, in main
    print(cfg.b.a or "NOPE")
  File "/Users/terry/anaconda3/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 297, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/Users/terry/anaconda3/lib/python3.7/site-packages/omegaconf/base.py", line 101, in _format_and_raise
    type_override=type_override,
  File "/Users/terry/anaconda3/lib/python3.7/site-packages/omegaconf/_utils.py", line 610, in format_and_raise
    _raise(ex, cause)
  File "/Users/terry/anaconda3/lib/python3.7/site-packages/omegaconf/_utils.py", line 591, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
  File "/Users/terry/anaconda3/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 295, in __getattr__
    return self._get_impl(key=key, default_value=DEFAULT_VALUE_MARKER)
  File "/Users/terry/anaconda3/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 353, in _get_impl
    node = self._get_node(key=key)
  File "/Users/terry/anaconda3/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 375, in _get_node
    self._validate_get(key)
  File "/Users/terry/anaconda3/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 128, in _validate_get
    key=key, value=value, cause=ConfigAttributeError(msg)
  File "/Users/terry/anaconda3/lib/python3.7/site-packages/omegaconf/base.py", line 101, in _format_and_raise
    type_override=type_override,
  File "/Users/terry/anaconda3/lib/python3.7/site-packages/omegaconf/_utils.py", line 675, in format_and_raise
    _raise(ex, cause)
  File "/Users/terry/anaconda3/lib/python3.7/site-packages/omegaconf/_utils.py", line 591, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ConfigAttributeError: Key 'a' is not in struct
	full_key: b.a
	reference_type=Any
	object_type=dict
```

**Expected behavior**

**Additional context**
hydra-core                         1.0.0
omegaconf                          2.0.2

**Comment by omry** [comment]
This is because Hydra sets OmegaConf to struct mode, which prevents access to non existent fields.
This is not a bug.
b does not have a field a, when you do 
```
cfg.b.a or "NOPE"
```

Python need to obtain the value of cfg.b.a before it can evaluate that it's false. In this case this fails because a does not exist.
