### ISSUE TITLE
Converting nested DictConfig/ListConfig to Python objects for JSON serialization

### ISSUE THREAD

**Issue by gchhablani** [omry/omegaconf#593]
Hi,

### Trying to save a config to JSON
I need to save a given configuration in JSON format. However, when I try this:

```yaml
#test1.yaml
main:
  value1: 1
  value2: [1,2,3]
```

```python
from omegaconf import OmegaConf
import json

config = OmegaConf.load('./test1.yaml')

with open('temp.json','w') as fil:
	json.dump(config,fil)
```
, it raises an error:
```python
Traceback (most recent call last):
  File "temp.py", line 12, in <module>
    json.dump(config,fil)
  File "/home/crocoder/anaconda3/lib/python3.8/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/home/crocoder/anaconda3/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/crocoder/anaconda3/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DictConfig is not JSON serializable.
```
The respective types are as follows:
```
Type of config:  <class 'omegaconf.dictconfig.DictConfig'>
Type of config.main:  <class 'omegaconf.dictconfig.DictConfig'>
Type of config.main.value1 :  <class 'int'>
Type of config.main.value2:  <class 'omegaconf.listconfig.ListConfig'>
```
### Convert Config to Dict
I tried converting the config into a dict as `config = dict(config)`:

Types are as follows:
```
Type of config:  <class 'dict'>
Type of config['main']:  <class 'omegaconf.dictconfig.DictConfig'>
Type of config['main'].value1 :  <class 'int'>
Type of config['main'].value2:  <class 'omegaconf.listconfig.ListConfig'>
```

Error:
```python
Traceback (most recent call last):
  File "temp.py", line 20, in <module>
    json.dump(d,fil)
  File "/home/crocoder/anaconda3/lib/python3.8/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/home/crocoder/anaconda3/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/home/crocoder/anaconda3/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/crocoder/anaconda3/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/crocoder/anaconda3/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DictConfig is not JSON serializable
```

### Conver inner DictConfig to Dict
Then I convert `config['main'] = dict(config['main'])`:
Types:
```
Type of config:  <class 'dict'>
Type of config['main']:  <class 'dict'>
Type of config['main']['value1'] :  <class 'int'>
Type of config['main']['value2']:  <class 'omegaconf.listconfig.ListConfig'>
```

Error:
```python
Traceback (most recent call last):
  File "temp.py", line 28, in <module>
    json.dump(d,fil)
  File "/home/crocoder/anaconda3/lib/python3.8/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/home/crocoder/anaconda3/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/home/crocoder/anaconda3/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/crocoder/anaconda3/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/crocoder/anaconda3/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/crocoder/anaconda3/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ListConfig is not JSON serializable
```

### Converting two-level nested ListConfig to list
Doing `config['main']['value2'] = list(config['main']['value2']))` makes it work because at this point everything is Python objects.

Ofcourse I can write a method to do it recursively, but is there already a way to convert several nested `Config` objects to Python objects easily?

**Comment by omry** [comment]
There is a fine method that is documented in the fine manual:

https://omegaconf.readthedocs.io/en/2.0_branch/usage.html#omegaconf-to-container

**Comment by gchhablani** [comment]
Thanks @omry.

**Comment by omry** [comment]
No problem.
I recommend that you read the documentation. It's not big and will help a lot.

**Comment by gchhablani** [comment]
I did go through, but I missed it somehow.  I'll check again, thanks.
