### ISSUE TITLE
yaml.dump() on a ListConfig gives AttributeError

### ISSUE THREAD

**Issue by twcostain** [omry/omegaconf#636]
**Describe the bug**
Calling `yaml.dump()` on a `ListConfig` causes yaml to throw
`AttributeError: 'str' object has no attribute '__name__'`

**To Reproduce**
Please provide a minimal repro.
This can include a small Python file, and potentially a few small config files.
If you have more than one file you can attach a zip file with everything to the issue.
```python
>>> import yaml
>>> from omegaconf import ListConfig
>>> a = ListConfig([1,2,3])
>>> a
[1, 2, 3]
>>> yaml.dump(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/costain/miniconda3/envs/aproxconv/lib/python3.8/site-packages/yaml/__init__.py", line 290, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/home/costain/miniconda3/envs/aproxconv/lib/python3.8/site-packages/yaml/__init__.py", line 278, in dump_all
    dumper.represent(data)
  File "/home/costain/miniconda3/envs/aproxconv/lib/python3.8/site-packages/yaml/representer.py", line 27, in represent
    node = self.represent_data(data)
  File "/home/costain/miniconda3/envs/aproxconv/lib/python3.8/site-packages/yaml/representer.py", line 52, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/home/costain/miniconda3/envs/aproxconv/lib/python3.8/site-packages/yaml/representer.py", line 342, in represent_object
    return self.represent_mapping(
  File "/home/costain/miniconda3/envs/aproxconv/lib/python3.8/site-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/home/costain/miniconda3/envs/aproxconv/lib/python3.8/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/costain/miniconda3/envs/aproxconv/lib/python3.8/site-packages/yaml/representer.py", line 199, in represent_list
    return self.represent_sequence('tag:yaml.org,2002:seq', data)
  File "/home/costain/miniconda3/envs/aproxconv/lib/python3.8/site-packages/yaml/representer.py", line 92, in represent_sequence
    node_item = self.represent_data(item)
  File "/home/costain/miniconda3/envs/aproxconv/lib/python3.8/site-packages/yaml/representer.py", line 52, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/home/costain/miniconda3/envs/aproxconv/lib/python3.8/site-packages/yaml/representer.py", line 342, in represent_object
    return self.represent_mapping(
  File "/home/costain/miniconda3/envs/aproxconv/lib/python3.8/site-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/home/costain/miniconda3/envs/aproxconv/lib/python3.8/site-packages/yaml/representer.py", line 52, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/home/costain/miniconda3/envs/aproxconv/lib/python3.8/site-packages/yaml/representer.py", line 342, in represent_object
    return self.represent_mapping(
  File "/home/costain/miniconda3/envs/aproxconv/lib/python3.8/site-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/home/costain/miniconda3/envs/aproxconv/lib/python3.8/site-packages/yaml/representer.py", line 52, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/home/costain/miniconda3/envs/aproxconv/lib/python3.8/site-packages/yaml/representer.py", line 331, in represent_object
    if function.__name__ == '__newobj__':
AttributeError: 'str' object has no attribute '__name__'
```

**Expected behavior**
I would expect the object to be dumped to yaml

**Additional context**
- [x] OmegaConf version: 2.0.6
- [x] Python version: 3.8.5
- [x] Operating system : Unbuntu 18.04

**Comment by twcostain** [comment]
I discovered this whilst trying to save a ListConfig as an hparam in Pytorch-Lightning

**Comment by omry** [comment]
Use OmegaConf.to_yaml to convert an OmegaConf object to yaml.
Alternatively you can convert the object to a plain container with OmegaConf.to_container and use yaml.dump on that.

**Comment by omry** [comment]
> I discovered this whilst trying to save a ListConfig as an hparam in Pytorch-Lightning

File an issue with am inimal repro against PTL if this is coming from their code. If this is coming from your code use the proper API.

**Comment by twcostain** [comment]
Looked into whats going wrong, and this is actually the same problem as #334. Its a bug/lack of support in pyyaml.
