### ISSUE TITLE
OmegaConf.resolve + readonly nested node + read_write not working

### ISSUE THREAD

**Issue by omry** [omry/omegaconf#694]
The following raises an error even though it shouldn't:

```python
from omegaconf import *

cfg = OmegaConf.create({"a": {"b": "${z}"}, "z": 99})
OmegaConf.set_readonly(cfg.a, True)

with read_write(cfg):
  OmegaConf.resolve(cfg)
```

```
Traceback (most recent call last):
  File "1.py", line 7, in <module>
    OmegaConf.resolve(cfg)
  File "/Users/omry/dev/omegaconf/omegaconf/omegaconf.py", line 786, in resolve
    omegaconf._impl._resolve(cfg)
  File "/Users/omry/dev/omegaconf/omegaconf/_impl.py", line 40, in _resolve
    _resolve_container_value(cfg, k)
  File "/Users/omry/dev/omegaconf/omegaconf/_impl.py", line 25, in _resolve_container_value
    _resolve(node)
  File "/Users/omry/dev/omegaconf/omegaconf/_impl.py", line 40, in _resolve
    _resolve_container_value(cfg, k)
  File "/Users/omry/dev/omegaconf/omegaconf/_impl.py", line 23, in _resolve_container_value
    node._set_value(resolved._value())
  File "/Users/omry/dev/omegaconf/omegaconf/nodes.py", line 34, in _set_value
    raise ReadonlyConfigError("Cannot set value of read-only config node")
omegaconf.errors.ReadonlyConfigError: Cannot set value of read-only config node
```

**Comment by Jasha10** [comment]
@omry, do you feel that the below should succeed?
```python
from omegaconf import *

cfg = OmegaConf.create({"a": {"b": "${z}"}, "z": 99})
OmegaConf.set_readonly(cfg.a, True)

with read_write(cfg):
  cfg.a.b = 123  # currently raises ReadonlyConfigError
```

In other words, should `read_write(cfg)` get a set of all subnodes and call `set_readonly(subnode, False)` on each one of them?

**Comment by omry** [comment]
> @omry, do you feel that the below should succeed?

No, it should fail because there is an explicit readonly flag on `a`.

> In other words, should read_write(cfg) get a set of all subnodes and call set_readonly(subnode, False) on each one of them?

This is not how it works.

Having looked at your comment, I now understand the issue.
I think this is expected because of the way flag overrides are working.
