### ISSUE TITLE
ENV support without additional wrappers

### ISSUE THREAD

**Issue by PerchunPak** [omry/omegaconf#938]
**Is your feature request related to a problem? Please describe.**
I want use human-readable config, without additional wrappers. Instead I need to wrap every option to `${oc.env:KEY,default_value}` and its looks ugly:
```yaml
token: ${oc.env:TOKEN,???}
locale: ${oc.env:LOCALE,en}
debug: ${oc.env:DEBUG,false}
verbose: ${oc.env:VERBOSE,false}
db_url: ${oc.env:DB_URL,sqlite:///data.db}
```
I want just:
```yaml
token: ???
locale: en
debug: false
verbose: false
db_url: sqlite:///data.db
```
Provide every option also with ENV variable can be helpful, example, for docker when the best will be just add arguments to `docker run` instead of add volumes and etc.

**Describe the solution you'd like**
Something like `overwrite_with_env` argument on `OmegaConf.create` and `OmegaConf.load` methods.

So this will just wrap every option to `"$\{oc.env:{0},{1}\}".format(key.upper(), value)` on parsing time.

**Describe alternatives you've considered**
Monkey patch as workaround, but this isn't good working, and produce additional bugs.

**Additional context**
[`python-decouple`](https://pypi.org/project/python-decouple/) provide support for ENV overwriting from box, but their architecture, in all cases, different from your.

**Comment by Jasha10** [comment]
Would something like this work for you?
```python
import os
from omegaconf import OmegaConf

cfg = OmegaConf.create(...)
for key, value in cfg.items():
    if key in os.environ:
        cfg[key] = os.environ[key]  # overwrite with environment var
```
This overwrites each value with the corresponding environment variable (if it is found).

**Comment by PerchunPak** [comment]
This wouldn't work if there is `???` default value in one of parameters.
```py
>>> from omegaconf import OmegaConf
>>> from dataclasses import dataclass
>>> @dataclass
... class Config:
...     a: str = "???"
... 
>>> cfg = OmegaConf.structed(Config)
>>> for key, value in cfg.items():
...     pass
... 
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "%PYTHON_DIR%\lib\site-packages\omegaconf\dictconfig.py", line 564, in items
    return dict(self.items_ex(resolve=True, keys=None)).items()
  File "%PYTHON_DIR%\lib\site-packages\omegaconf\dictconfig.py", line 590, in items_ex
    value = self[key]
  File "%PYTHON_DIR%\lib\site-packages\omegaconf\dictconfig.py", line 377, in __getitem__
    self._format_and_raise(key=key, value=None, cause=e)
  File "%PYTHON_DIR%\lib\site-packages\omegaconf\base.py", line 231, in _format_and_raise
    format_and_raise(
  File "%PYTHON_DIR%\lib\site-packages\omegaconf\_utils.py", line 873, in format_and_raise
    _raise(ex, cause)
  File "%PYTHON_DIR%\lib\site-packages\omegaconf\_utils.py", line 771, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "%PYTHON_DIR%\lib\site-packages\omegaconf\dictconfig.py", line 371, in __getitem__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "%PYTHON_DIR%\lib\site-packages\omegaconf\dictconfig.py", line 453, in _get_impl
    return self._resolve_with_default(
  File "%PYTHON_DIR%\lib\site-packages\omegaconf\basecontainer.py", line 96, in _resolve_with_default
    raise MissingMandatoryValue("Missing mandatory value: $FULL_KEY")
omegaconf.errors.MissingMandatoryValue: Missing mandatory value: a
    full_key: a
    object_type=Config
```
Note that I even didn't touched `os` package.

**Comment by Jasha10** [comment]
Sorry my original solution did not handle missing values properly. Please give this a try:
import os
from omegaconf import OmegaConf
```
cfg = OmegaConf.create(...)
for key in cfg:
    if key in os.environ:
        cfg[key] = os.environ[key]  # overwrite with environment var
```
