### ISSUE TITLE
[regression?] type `Sequence` no longer supported in OC 2.2?

### ISSUE THREAD

**Issue by jieru-hu** [omry/omegaconf#991]
# repro
```python
from dataclasses import dataclass, field
from typing import Optional, Sequence
import hydra

@dataclass()
class MLMRobertaModelConf:
    _target_: str = ""
    decoder_hidden_dims: Optional[Sequence[int]] = field(default_factory=lambda: [768])

class MLMRobertaModel:
    """Masked Languaged Model Roberta"""

    def __init__(
        self,
        decoder_hidden_dims: Optional[Sequence[int]] = [768],  # noqa
    ) -> None:
        pass

model_conf=MLMRobertaModelConf(
    _target_="__main__.MLMRobertaModel",
    decoder_hidden_dims=[768],
)

if __name__ == "__main__":
    model = hydra.utils.instantiate(model_conf, _recursive_=False)
    print(model)
```

## on OC 2.1.1
```
 % pip freeze | grep omegaconf 
omegaconf==2.1.1
```
```
 % python repro.py             
<__main__.MLMRobertaModel object at 0x1018d4280>
```

## on OC 2.2.2
```
% pip freeze | grep omegaconf 
omegaconf==2.2.2
```

```
 % python repro.py             
Traceback (most recent call last):
  File "/Users/jieru/workspace/hydra/examples/tutorials/repro/repro.py", line 30, in <module>
    model = hydra.utils.instantiate(model_conf, _recursive_=False)
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 202, in instantiate
    config = OmegaConf.structured(config, flags={"allow_objects": True})
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/omegaconf.py", line 123, in structured
    return OmegaConf.create(obj, parent, flags)
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/omegaconf.py", line 176, in create
    return OmegaConf._create_impl(
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/omegaconf.py", line 882, in _create_impl
    format_and_raise(node=None, key=None, value=None, msg=str(e), cause=e)
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/_utils.py", line 793, in format_and_raise
    _raise(ex, cause)
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/_utils.py", line 771, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/omegaconf.py", line 843, in _create_impl
    return DictConfig(
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 111, in __init__
    format_and_raise(node=None, key=key, value=None, cause=ex, msg=str(ex))
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/_utils.py", line 873, in format_and_raise
    _raise(ex, cause)
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/_utils.py", line 771, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 94, in __init__
    self._set_value(content, flags=flags)
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 649, in _set_value
    raise e
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 646, in _set_value
    self._set_value_impl(value, flags)
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 676, in _set_value_impl
    data = get_structured_config_data(value, allow_objects=ao)
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/_utils.py", line 481, in get_structured_config_data
    return get_dataclass_data(obj, allow_objects=allow_objects)
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/_utils.py", line 401, in get_dataclass_data
    d[name] = _maybe_wrap(
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/omegaconf.py", line 1070, in _maybe_wrap
    return _node_wrap(
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/omegaconf/omegaconf.py", line 1028, in _node_wrap
    elif issubclass(ref_type, Enum):
omegaconf.errors.ConfigTypeError: issubclass() arg 1 must be a class
    full_key: 
    object_type=None
```

**Comment by Jasha10** [comment]
I consider this to be a bug in OmegaConf 2.1 (rather than a regression).
OmegaConf 2.1 would normally not allow `typing.Sequence`. For example, the following gives an error in v2.1:
```python
@dataclass
class MLMRobertaModelConf:
    decoder_hidden_dims: Sequence[int]

cfg = OmegaConf.structured(MLMRobertaModelConf)  # raises ConfigTypeError
```
However, if a `default_factory` is used, then `ConfigTypeError` is *not* raised. I consider failure to raise to be a bug:
```python
@dataclass
class MLMRobertaModelConf:
    decoder_hidden_dims: Sequence[int] = field(default_factory=lambda: [768])

cfg = OmegaConf.structured(MLMRobertaModelConf)  # does not raise (though it should raise)
```

@jieru-hu, would it be possible to fix our internal error by replacing `typing.Sequence` annotations with `typing.List` annotations?

> ```
> omegaconf.errors.ConfigTypeError: issubclass() arg 1 must be a class
>     full_key: 
>     object_type=None
> ```
I'd prefer to put in a PR that makes the above error message clearer (saying `typing.Sequence` is not supported) rather than opting to treat `typing.Sequence` as an alias for `typing.List`.
